'''
Created on 14 mar 2017

@author: francescocerone
'''


class AnimationList(object):
    
    animationListMap = {
                #"a" : "a.gif",
        #"b" : "b.gif",
        #"c" : "c.gif",
        #"d" : "d.gif",
        "e" : "e.gif",
        "f" : "f.gif",
        #"g" : "g.gif",
        #"h" : "h.gif",
        #"ele" : "ele.gif",
        #"m" : "m.gif",
        #"n" : "n.gif",
        "o" : "o.gif",
        #"p" : "p.gif",
        #"q" : "q.gif",
        "r" : "r.gif",
        "s" : "s.gif",
        #"t" : "t.gif",
        "u" : "u.gif",
        "v" : "v.gif",
        "z" : "z.gif",
        "0a" : "0a.gif",
        "0b" : "0b.gif",
        #"0c" : "0c.gif",
        #"0d" : "0d.gif",
        #"0e" : "0e.gif",
        "0f" : "0f.gif",
        #"0g" : "0g.gif",
        "0h" : "0h.gif",
        "0i" : "0i.gif",
        "0l" : "0l.gif",
        "0m" : "0m.gif",
        #"0n" : "0n.gif",
        #"0o" : "0o.gif",
        #"0p" : "0p.gif",
        #"0q" : "0q.gif",
        "0r" : "0r.gif",
        #"0s" : "0s.gif",
        #"0t" : "0t.gif",
        #"0u" : "0u.gif",
        "0v" : "0v.gif",
        #"0z" : "0z.gif",
        #"1a" : "1a.gif",
        "1b" : "1b.gif",
        #"1c" : "1c.gif",
        #"1d" : "1d.gif",
        #"1e" : "1e.gif",
        #"1f" : "1f.gif",
        #"1g" : "1g.gif",
        #"1h" : "1h.gif",
        #"1i" : "1i.gif",
        #"1l" : "1l.gif",
        "1m" : "1m.gif",
        #"1n" : "1n.gif",
        #"1o" : "1o.gif",
        #"1p" : "1p.gif",
        #"1q" : "1q.gif",
        "1v" : "1v.gif",
        #"1z" : "1z.gif",
        "2a" : "2a.gif",
        "logo1" : "logo1.gif",
        "logo2" : "logo2.gif",
        "logo3" : "logo3.gif",
        "logo4" : "logo4.gif",
        #"2c": "2c.gif",
        #"2d" : "2d.gif",
        #"2e" : "2e.gif",
        #"2f" : "2f.gif",
        #"2g" : "2g.gif",
        #"2h" : "2h.gif",
        #"2i" : "2i.gif",
        #"2l" : "2l.gif",
        #"2m" : "2m.gif",
        #"ev_groove_stacco1" : "ev_groove_stacco1.gif",
        #"ev_intro1" : "ev_intro1.gif",
        #"ev_intro2" : "ev_intro2.gif",
        #"ev_intro3_chiaro" : "ev_intro3_chiaro.gif",
        #"ev_intro3" : "ev_intro3.gif",
        #"ev_intro4" : "ev_intro4.gif",
        #"ev_lancio" : "ev_lancio.gif",
        #"ev_pausa1" : "ev_pausa1.gif",
        #"ev_pausa2" : "ev_pausa2.gif",
        #"ev_rit1" : "ev_rit1.gif",
        #"ev_rit2" : "ev_rit2.gif",
        #"ev_stacco" : "ev_stacco.gif",
        #"ev_ultimo_stacco" : "ev_ultimo_stacco.gif",
        #"G1" : "G1.gif",
        #"G2" : "G2.gif",
        #"G3" : "zzG3.gif",
        #"G4" : "G4.gif",
        #"franco1" : "franco1",
        #"franco2" : "franco2",
        #"franco3" : "franco3",
        #["franco4" : "franco4",
        #"syria" : "syria"
        "spider" : "spider"
    }
